name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set build arguments
        id: vars
        run: |
          DOTENV_LINTER_VERSION=$(cat VERSION)
          BUILD_DATE=$(date +%Y-%m-%dT%T%z)
          BUILD_REVISION=$(git rev-parse --short HEAD)
          echo "DOTENV_LINTER_VERSION=$DOTENV_LINTER_VERSION" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "BUILD_REVISION=$BUILD_REVISION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Alpine version for multiple platforms
      - name: Build and push Alpine version
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dotenv-linter:alpine
            ${{ secrets.DOCKERHUB_USERNAME }}/dotenv-linter:latest-alpine
            ${{ secrets.DOCKERHUB_USERNAME }}/dotenv-linter:${{ env.DOTENV_LINTER_VERSION }}-alpine
          build-args: |
            DOTENV_LINTER_VERSION=${{ env.DOTENV_LINTER_VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ env.BUILD_REVISION }}

      # Build and push BusyBox version for multiple platforms
      - name: Build and push BusyBox version
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dotenv-linter:busybox
            ${{ secrets.DOCKERHUB_USERNAME }}/dotenv-linter:latest-busybox
            ${{ secrets.DOCKERHUB_USERNAME }}/dotenv-linter:${{ env.DOTENV_LINTER_VERSION }}-busybox
          build-args: |
            DOTENV_LINTER_VERSION=${{ env.DOTENV_LINTER_VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ env.BUILD_REVISION }}
