name: PR Validation

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set build arguments
        uses: ./.github/actions/set-build-args

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build Alpine version
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            DOTENV_LINTER_VERSION=${{ env.DOTENV_LINTER_VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ env.BUILD_REVISION }}
          target: alpine-version

      - name: Build BusyBox version
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            DOTENV_LINTER_VERSION=${{ env.DOTENV_LINTER_VERSION }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ env.BUILD_REVISION }}
          target: busybox-version
